"""empty message

Revision ID: 578ecea55a7e
Revises: 7fc6c0a8384c
Create Date: 2020-05-03 23:03:10.612050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578ecea55a7e'
down_revision = '7fc6c0a8384c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('observation_response', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('observation_response', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
