"""empty message

Revision ID: 59351e523f58
Revises: 02c70247a8c9
Create Date: 2020-05-02 12:21:26.755885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59351e523f58'
down_revision = '02c70247a8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('student_assignments',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], )
    )
    op.drop_table('student_assignmetns')
    op.add_column('experiment', sa.Column('device_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'experiment', 'device', ['device_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'experiment', type_='foreignkey')
    op.drop_column('experiment', 'device_id')
    op.create_table('student_assignmetns',
    sa.Column('assignment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], name='student_assignmetns_assignment_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='student_assignmetns_student_id_fkey')
    )
    op.drop_table('student_assignments')
    op.drop_table('device')
    # ### end Alembic commands ###
