"""empty message

Revision ID: 7fc6c0a8384c
Revises: 8ddac6a39358
Create Date: 2020-05-03 20:04:54.773307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc6c0a8384c'
down_revision = '8ddac6a39358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignment_responses', 'response',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignment_responses', 'response',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
