"""empty message

Revision ID: 8ddac6a39358
Revises: 3b7076bf25e3
Create Date: 2020-05-03 17:35:39.747307

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ddac6a39358'
down_revision = '3b7076bf25e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observation_response',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('submitted', sa.Date(), nullable=True),
    sa.Column('editable', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observation.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.alter_column('assignment_responses', 'submitted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignment_responses', 'submitted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_table('observation_response')
    # ### end Alembic commands ###
